### ISSUE TITLE
Parse issue with literal struct notation

### ISSUE THREAD

**Issue by atuttle** [cfparser/cfparser#11]
Not sure how you want bugs reported, so let's start with what's easiest for me in my setup and if you need more info then let me know... so I don't have to jump through extra hoops just because I think that's what you want. :)

Here's another parse error manifesting in Sublime Text through CFLint and SublimeLinter-contrib-CFLint:

![image](https://cloud.githubusercontent.com/assets/46990/10455360/d5dcbe26-7188-11e5-84a4-1c491e5a395f.png)

It's an inline literal structure being passed as the 2nd argument to the constructor of a new CFC instance (`new util.iQuery()`).

Possibly complicating things is my preferred style of comma-first lists?

**Comment by ryaneberly** [comment]
@atuttle 
No problem.  You are reporting them.  That's a great start. :-).  The rest is just details.

I just need to see an example of the code that is not parsing.  If it is a weird language thing, pointing to the language spec that explains it would help.

If you are feeling ambitious, you can branch and add the example into
https://github.com/cfparser/cfparser/tree/master/cfml.parsing/src/test/resources/cfml/tests
That folder contains code samples along with the expected parsing results.  You can leave the expected results out initially - the TestFiles unit test will generate it.

**Comment by ryaneberly** [comment]
merged the parseerr branch to master.
