### ISSUE TITLE
Add way to override expressionVisitor and scriptVisitor

### ISSUE THREAD

**Issue by lramirez925** [cfparser/cfparser#117]
I have been looking at this project as potentially a base for a project and I would like to use the CFMLParser class but with a different visitor. Is this currently possible and I don't see it or would it be difficult to add? 

Minimum changes would be to make those fields protected so anyone can extend the CFMLParser and provide a way to set those values.

**Comment by ryaneberly** [comment]
That shouldn't be too difficult, separation between the parser and the visitor is core to ANTLR.  You can see how the visitor and parser( and resulting parsetree) interact in https://github.com/cfparser/cfparser/blob/fa0881fe03ac81a8aca5fad12221fbb624d38c2e/cfml.parsing/src/test/java/cfml/parsing/TestFiles.java
as a reference.

If you write your own visitor, it should just work
