### ISSUE TITLE
support ordered structs with literal notation

### ISSUE THREAD

**Issue by ryaneberly** [cfparser/cfparser#124]
Also, and affecting the Adobe Coldfusion as well,
the posibility to declare ordered structs with literal notation doesn't work.
Ej. var my_ordered_struct = [ a=1, b=2 ];

**Comment by KamasamaK** [comment]
Please make all of the following work.
```
orderedStructEquals = [ a=1, b=2 ];
orderedStructColon = [ a:1, b:2 ];
emptyOrderedStructEquals = [=];
emptyOrderedStructColon = [:];
```

**Comment by ryaneberly** [comment]
added to develop branch
