### ISSUE TITLE
Constructor that CFEclipse uses does not run initDictionaries

### ISSUE THREAD

**Issue by denuno** [cfparser/cfparser#21]
What the subject says

**Comment by denuno** [comment]
Thanks!

**Comment by ryaneberly** [comment]
You're welcome,  are you putting this back into CFEclipse?

**Comment by denuno** [comment]
Yep, it's in the latest dev version... adding cflint as a builder, too, so it'll automatically add warnings and stuff for the project.

**Comment by ryaneberly** [comment]
Nice!
