### ISSUE TITLE
mismatched input when mixing hash and quotes

### ISSUE THREAD

**Issue by bardware** [cfparser/cfparser#27]
Hi,

I ran CFLint on a Coldfusion project and understand it uses your cfparser to tokenise the CFM scripts.
It logged plenty errors like ` mismatched input 'YY_MM_DD' expecting {<EOF>, CONTAINS, GT, GTE, LTE, LT, EQ, NEQ, OR, EQV, XOR, AND, '++', '--', '||', '&&', '?'}`
I believe the reason is the use of double quotes inside a set of double quotes. In this case it is actually valid as it's used inbetween a set of hash signs.
`<cfset filename = "#dateformat( Now(), "YY_MM_DD" )#_#TimeFormat( Now(), "HH_mm" )#_Company.xls">`

Is there something you can do about it?

Thank you,
Bernhard

**Comment by ryaneberly** [comment]
cfparser 2.2.1 released to maven.

Thanks Bernard

**Comment by bardware** [comment]
Version 2.2.1 became available on http://mvnrepository.com/artifact/com.github.cfparser/cfparser
I modified the cfparser version number in CFLint pom.xml in my local repository to use the 2.2.1 version. It compiled fine and the error file size reduced dramatically. Looks good. Thanks alot.

**Comment by ryaneberly** [comment]
Good to know.  That was my next step.  Thanks for testing it.
