### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by remy-tiitre** [cfparser/cfparser#29]
I think the parser does not take into consideration that the double-quotation marks ("), single-quotation mark ('), and number sign (#) characters have special meaning to ColdFusion. To include any of them in a string, double the character; for example, use ## to represent a single # character.

The need to escape the single- and double-quotation marks is context sensitive. Inside a double-quoted string, you do not need to escape single-quotation mark (apostrophe) characters. Inside a single-quoted string, you do not escape double-quotation mark characters.

**Comment by remy-tiitre** [comment]
I think the lexer is incorrect, it should have '\'' (~'\'' | '\'\'')* '\'' and '"' (~'"' | '""')* '""' as values for single and double quotes.

**Comment by ryaneberly** [comment]
Good point.  thanks
Ref:http://help.adobe.com/en_US/ColdFusion/9.0/Developing/WSc3ff6d0ea77859461172e0811cbec0999c-7ffb.html

If you get to it before I do, send out a pull request.

**Comment by denuno** [comment]
Whoops, I got to the string stuff last week but forgot to send a pull!  The ## handling is still off though.

**Comment by ryaneberly** [comment]
Interesting.  I thought the double hash was the one I had implemented..

**Comment by denuno** [comment]
On further review, the double hash was fine-- I had been using the hashParsingInputStream deal in CFEclipse, which is no longer needed (yay!).

I still need to run these changes on CFLint to see how it does with them, but it seems like strings with escaped terminators are a go.

**Comment by ryaneberly** [comment]
Wonderful. Thanks!
