### ISSUE TITLE
Antlr3 to Antlr4 Grammar Upgrades

### ISSUE THREAD

**Issue by jjames967** [cfparser/cfparser#4]
I'll be looking into converting the grammar files from Antlr3.4 to Antlr4.x over the next two weeks. If anyone comes across any good references please let me know!

**Comment by jjames967** [comment]
On ANTLR4 branch receiving errors: 
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/CFMLParser.java:[38,26] package cfml.parsing.utils does not exist
[ERROR] /C:/cfparser/cfml.parsing/target/generated-sources/antlr4/cfml/CFSCRIPTParser.java:[3634,70] incompatible types: cfml.CFSCRIPTParser.TernaryContext cannot be converted to cfml.CFSCRIPTParser.B
aseExpressionContext
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/CFMLParser.java:[357,17] cannot find symbol
  symbol:   variable TestUtils
  location: class cfml.parsing.CFMLParser

**Comment by ryaneberly** [comment]
Fixed.  I fleshed out the CFExpressionVisitor a bit more.  yikes.  the
grammar is starting to look like the easy part!

**Comment by jjames967** [comment]
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/util/SourceReader.java:[36,8] duplicate class: cfml.parsing.util.SourceRead
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/util/FastMap.java:[42,8] duplicate class: cfml.parsing.util.FastMap
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/util/CFException.java:[39,8] duplicate class: cfml.parsing.util.CFException
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/PoundSignFilterStreamException.java:[32,8] duplicate class: cfml.pars
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/CaseSensitiveMap.java:[32,8] duplicate class: cfml.parsing.util.CaseS
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/PoundSignFilterStream.java:[44,8] duplicate class: cfml.parsing.util.
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/SequencedHashMap.java:[52,8] duplicate class: cfml.parsing.util.Seque
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/ParseUtil.java:[32,8] duplicate class: cfml.parsing.util.ParseUtil

I have looked at this before, but not to long. It's when running tests on cfparser.

**Comment by jjames967** [comment]
I can't get cfparser antlr branch to compile even when trying to skip tests.

**Comment by ryaneberly** [comment]
mmm ..did you try.  mvn clean install

**Comment by jjames967** [comment]
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/util/SourceReader.java:[36,8] duplicate class: cfml.parsing.util.SourceReader
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/util/FastMap.java:[42,8] duplicate class: cfml.parsing.util.FastMap
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/util/CFException.java:[39,8] duplicate class: cfml.parsing.util.CFException
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/PoundSignFilterStreamException.java:[32,8] duplicate class: cfml.parsing.util.PoundSignFilterStreamException
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/CaseSensitiveMap.java:[32,8] duplicate class: cfml.parsing.util.CaseSensitiveMap
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/PoundSignFilterStream.java:[44,8] duplicate class: cfml.parsing.util.PoundSignFilterStream
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/SequencedHashMap.java:[52,8] duplicate class: cfml.parsing.util.SequencedHashMap
[ERROR] /C:/cfparser/cfml.parsing/src/main/java/cfml/parsing/utils/ParseUtil.java:[32,8] duplicate class: cfml.parsing.util.ParseUtil
[INFO] 8 errors

**Comment by jjames967** [comment]
It was an ID10T error. I had some changes that I didn't revert.

**Comment by ryaneberly** [comment]
No problem. :-).

**Comment by ryaneberly** [comment]
merged to master
