### ISSUE TITLE
throw as keyword

### ISSUE THREAD

**Issue by boughtonp** [cfparser/cfparser#45]
This has no errors:
```
<cfscript>
		if ( NOT VarUtils.ExistsWithLen(rc,'mode') )
			throw ("Unknown mode.");
</cfscript>
```

This reports an expected semi-colon:
```
<cfscript>
		if ( NOT VarUtils.ExistsWithLen(rc,'mode') )
			throw "Unknown mode.";
</cfscript>
```

Both are valid syntax, but if it wasn't, can the parser be taught to expect an open paren after a known built-in function instead of semicolon?

**Comment by denuno** [comment]
I think a more general solution would be easier if we fed the functions in from an external source like we used to, right now the tokens are hard-coded, so it would be pretty hard to teach the parser the difference (AFAIK).
