### ISSUE TITLE
cfcontinue is not treated as solo tag

### ISSUE THREAD

**Issue by boughtonp** [cfparser/cfparser#46]
```
<cfloop query="qResults">
	<cfif refind( "^\.", qResults.name )>
		<cfcontinue>
	</cfif>
</cfloop>
```
Without being self-closed (as above), it returns three errors:
`cfloop is missing a closing tag
Something in here is (probably) missing a closing tag or a closing ">" and thus totally borking the parse!`

`cfif is missing a closing tag`

`Closing tag '</cfif>' does not match the current parent item: 'cfcontinue'`

With `<cfcontinue/>` instead it only has the last one of those three.

**Comment by ryaneberly** [comment]
I think these are CFE issues, not issues with the cfparser lib itself.  Can you confirm?

**Comment by boughtonp** [comment]
Everything I've raised was found in CFE - I assumed being a parser-level issue meant it was cfparser, but I don't actually know where the boundary lies.

**Comment by ryaneberly** [comment]
Fixed here.
