### ISSUE TITLE
Attributecollection on tags with action-based required attributes (cfftp, cffile)

### ISSUE THREAD

**Issue by boughtonp** [cfparser/cfparser#47]
```<cfftp action="open" connection="objConnection" attributeCollection="#objFTPProperties#" timeout="300" />```

> The attribute 'server' is required for the <cfftp> tag. (Found: [connection, action, attributecollection, timeout])
> The attribute 'username' is required for the <cfftp> tag. (Found: [connection, action, attributecollection, timeout])
> The attribute 'password' is required for the <cfftp> tag. (Found: [connection, action, attributecollection, timeout])

Checked cffile and got a related error, but cffunction with attributecollection works, so assume it's for tags where action sets the mode.

**Comment by ryaneberly** [comment]
Thanks for reporting this issue.  I'm having a bit of difficulty replicating the messages.  Can you describe where you are seeing them and how to duplicate the behaviour?

**Comment by denuno** [comment]
That's an error for CFE, unrelated to cfparser.

Den

**Comment by ryaneberly** [comment]
thanks @denuno
