### ISSUE TITLE
</cfmail> does not match the current parent item: 'cfdump'

### ISSUE THREAD

**Issue by bardware** [cfparser/cfparser#53]
Does it relate to the parser or to the CFEclipse project? I have CFDump Tags in a mail for debugging purposes in a CFcatch. The reports don't look good.

![snipimage](https://cloud.githubusercontent.com/assets/802702/15808359/637065e2-2b76-11e6-875b-5a442266ecd1.JPG)

**Comment by ryaneberly** [comment]
@denuno, are these CFE issues as well?

**Comment by ryaneberly** [comment]
see #46. This should be working now.

**Comment by bardware** [comment]
I've seen it working after a [commit](https://github.com/cfeclipse/cfeclipse/issues/73) by @denuno :)
