### ISSUE TITLE
Failing to package -  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar (attach-javadocs) on project cfml.dictionary

### ISSUE THREAD

**Issue by jjames967** [cfparser/cfparser#6]
The java files are not updated to recent javadoc requirements. This needs to be fixed in order to deploy future version.

Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar (attach-javadocs) on project cfml.dictionary: MavenReportException: Error while creating archive:
Exit code: 1 - C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:177: warning: no @param for prefs
public static void initDictionaries(DictionaryPreferences prefs) {
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:194: warning: no description for @param
* @param forDictionary
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:195: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:240: warning: no description for @param
* @param versionkey
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:256: warning: no description for @param
* @param versionkey
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:257: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:378: warning: no description for @param
* @param cachekey
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:379: warning: no description for @param
* @param livekey
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:430: warning: no description for @param
* @param key
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\DictionaryManager.java:431: warning: no description for @param
* @param sd
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Function.java:112: warning: no @return
public String getInsertion() {
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Function.java:72: error: @param name not found
* @param type
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Function.java:75: warning: no @param for returntype
public Function(String name, String returntype, byte creator) {
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Function.java:75: warning: no @param for creator
public Function(String name, String returntype, byte creator) {
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\ISyntaxDictionary.java:70: warning: no description for @param
* @param start
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\ISyntaxDictionary.java:79: warning: no description for @param
* @param start
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\ISyntaxDictionary.java:87: warning: no description for @param
* @param functionName
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\ISyntaxDictionary.java:95: warning: no description for @param
* @param functionName
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Parameter.java:72: error: reference not found
* @see #cfml
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Parameter.java:74: warning - Tag @see: can't find cfml in cfml.dictionary.Parameter
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Parameter.java:92: error: bad HTML entity
*         <li><code>PARAM_REQUIRED</code> - Parameter required & triggered (will be
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Parameter.java:141: warning: no description for @param
* @param availParams
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Parameter.java:207: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Parameter.java:216: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Parameter.java:49: error: bad HTML entity
* The Parameter is required (generally and'ed with PARAM_TRIGGERED to indicate that it is triggered & required
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:81: error: @param name not found
* @param filename
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:81: warning: no description for @param
* @param filename
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:83: warning: no @param for url
public void loadDictionary(String url) {
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:338: error: @param name not found
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:338: warning: no description for @param
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:339: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:349: warning: no description for @param
* @param functionname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:350: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:361: warning: no description for @param
* @param functionname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:362: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:380: warning: no description for @param
* @param name
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:394: warning: no description for @param
* @param name
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:395: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:414: warning: no description for @param
* @param name
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:415: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\SyntaxDictionary.java:50: error: bad HTML entity
*         provides the methods for gaining access to the dictionary's defined functions & tags, plus access to the
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Tag.java:122: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Tag.java:134: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Tag.java:164: warning: no @return
public boolean isHybrid() {
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Tag.java:171: warning: no @return
public boolean allowsAnyAttribute() {
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Tag.java:178: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Trigger.java:145: error: bad HTML entity
* @return PARAM_TRIGGERD | PARAM_REQUIRED (triggered & required) PARAM_TRIGGERED (simply triggered, therefore
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Trigger.java:198: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\Trigger.java:10: error: unknown tag: cffile
* on the tag <cffile> the parameter 'source' is available when the 'append' attribute is set to either: copy,move or
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\CFSyntaxDictionary.java:57: error: @param name not found
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\CFSyntaxDictionary.java:57: warning: no description for @param
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\CFSyntaxDictionary.java:58: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\CFSyntaxDictionary.java:67: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\HTMLSyntaxDictionary.java:42: error: @param name not found
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\HTMLSyntaxDictionary.java:42: warning: no description for @param
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\HTMLSyntaxDictionary.java:43: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\JSSyntaxDictionary.java:57: error: @param name not found
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\JSSyntaxDictionary.java:57: warning: no description for @param
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\JSSyntaxDictionary.java:58: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\JSSyntaxDictionary.java:67: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\JSSyntaxDictionary.java:76: error: @param name not found
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\JSSyntaxDictionary.java:76: warning: no description for @param
* @param elementname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\JSSyntaxDictionary.java:77: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\JSSyntaxDictionary.java:86: warning: no description for @param
* @param functionname
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\JSSyntaxDictionary.java:87: warning: no description for @return
* @return
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\SQLSyntaxDictionary.java:57: error: @param name not found
* @param keywordFilename
^
C:\cfparser\cfml.dictionary\src\main\java\cfml\dictionary\syntax\SQLSyntaxDictionary.java:60: warning: no @param for keywordsURL
public void loadKeywords(URL keywordsURL) {
^

Command line was: "C:\Program Files\Java\jdk1.8.0_31\jre\..\bin\javadoc.exe" @options @packages

**Comment by ryaneberly** [comment]
fixed the errors. We'll leave the warnings alone

**Comment by rsharm7** [comment]
How did you solve the issue?

**Comment by ryaneberly** [comment]
@rsharm7 
  If I recall correctly, I manually added the missing javadoc attributes.
