### ISSUE TITLE
structure shorthand can be defined with = instead of :

### ISSUE THREAD

**Issue by displague** [cfparser/cfparser#63]
```coldfusion
<cfscript>
// valid structure definition
test = {
 foO : "bar",
 tisK = "task",
 "quoteD": "value",
 "alsO"= "value2"
};
</cfscript>
```

| struct | |
| :--- | :--- |
| FOO |	bar |
| TISK |	task |
| alsO |	value2 |
| quoteD |	value |

The parser says `End of statement(;) expected instead of ,`

http://trycf.com/gist/a02b0a02956492936deb057b78e5b4f6/acf11?theme=monokai

https://www.bennadel.com/blog/1993-using-dynamic-keys-in-coldfusion-9-s-implicit-struct-creation.htm

**Comment by displague** [comment]
It seems the parser only complains if you put a space around the equal sign.

**Comment by displague** [comment]
Err.. I am getting this cfparse error in real code, but can't seem to reproduce it in a test script.

**Comment by displague** [comment]
I had a javascript style stray comma -- `{ test="test", }` .. Even CF failed to parse.  Sorry.

+1 for CFParser.

**Comment by ryaneberly** [comment]
Glad you found it :-)

On Fri, Nov 11, 2016 at 2:46 PM, Marques Johansson <notifications@github.com
