### ISSUE TITLE
Test QueryParams

### ISSUE THREAD

**Issue by msp1kpj** [cfparser/cfparser#70]
I added There 2 check to the /cfml.parsing/src/test/java/cfml/parsing/cfmentat/tag/TestGetStartTagEnd.java

I am getting 

[main] ERROR net.htmlparser.jericho - StartTag cfqueryparam at (r1,c1,p0) contains attribute name with invalid first character at position (r1,c26,p25)

From digging into the issue it looks like it is comparing "cfqueryparam" to the "cfquery" tag.
```
public void testAllStartTags_length_queryparamWithVariable() {
		String rawSource = "<cfqueryparam value='#arguments.memberId#' cfsqltype='cf_sql_varchar'/>";
		
		StartTag cftag = parseAndGetFirstTag(rawSource, StartTagTypeCfQueryParam.INSTANCE);
		
		assertEquals(rawSource.length(), cftag.getEnd());
	}
	
	public void testAllStartTags_length_queryparamWithNoAttribute() {
		String rawSource = "<cfqueryparam value='sd' />";
		
		StartTag cftag = parseAndGetFirstTag(rawSource, StartTagTypeCfQueryParam.INSTANCE);
		
		assertEquals(rawSource.length(), cftag.getEnd());
	}
```

**Comment by ryaneberly** [comment]
I think this is a bug in 
net.htmlparser.jericho.Tag.getNextTagUncached(Source, int, TagType, int)

It does not expect two tags to start with the same string.

**Comment by ryaneberly** [comment]
It was not loading the tags from the dictionary.  This is resolved in the dev branch.  Thanks for reporting it.
