### ISSUE TITLE
Issue with the grammar. 

### ISSUE THREAD

**Issue by lramirez925** [cfparser/cfparser#99]
I tried using the grammar and I am getting a few errors. Would you mind helping me with how you are generating the actual parser code? 

I am getting an error with the lexar on line 4 because it starts with a -> and an error 374 for the same reason. Is there something special you have to do to use this Lexar file? I am trying to debug it with antlrworks2

I would also like to see if you would be interested in pulling the grammar out and having a separate project to allow more than just java parsers.

**Comment by ryaneberly** [comment]
@lramirez925 
    I'm not sure what the issue is in Antlrworks2.  cfparser is  a maven project, so you can build it with 

       mvn build

    I personally use Eclipse with the Antlr plugin.

    I don't know the implications of generating a parser in another language from antlr.  Feel it a try and let me know what you find.

**Comment by lramirez925** [comment]
So AntlrWorks2 is just a debugging tool for the grammars and that may be the problem. 

I followed the steps to generate the parser and lexar code using the javascript target and there was a lot of problems. 1 of them being the use of the _modeStack in the # definition. 
I will try the eclipse plugin and see if that gives me the same errors.

**Comment by ryaneberly** [comment]
Ah yes, we did some peeking at the mode stack to make some decisions.  If you translate that piece into the javascript equivalent, you may be ok
